.. Central place for all links

.. _`Unyson`: http://unyson.themefuse.com
.. _`WordPress`: http://wordpress.org
.. _`WordPress Documentation`: http://codex.wordpress.org/Main_Page
.. _`Download`: https://github.com/ThemeFuse/Unyson-Framework/releases
.. _`WordPress Coding Standards`: http://make.wordpress.org/core/handbook/coding-standards/
.. _`WordPress Minimum Requirements`: http://wordpress.org/about/requirements/
.. _`@internal`: http://www.phpdoc.org/docs/latest/references/phpdoc/tags/internal.html
.. _`md5`: https://www.google.md/#q=what+is+md5
.. _`bootstrap`: http://getbootstrap.com/
.. _`add_meta_box()`: http://codex.wordpress.org/Function_Reference/add_meta_box#Parameters
.. _`General Public License`: http://wordpress.org/about/gpl/
.. _`Nicolas Gallagher`: http://nicolasgallagher.com/about/
.. _`ThemeFuse`: http://themefuse.com

